server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: now-api-interface
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: localhost
    database: 0
  main:
    web-application-type: reactive
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: nowcode-gateway-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848